CREATE TABLE Product (
    Pno INT(9) PRIMARY KEY AUTO_INCREMENT,
    Pcode VARCHAR(64) NOT NULL,
    Pname VARCHAR(64) NOT NULL,
    Pcno INT(9),
    PSpec VARCHAR(64),
    PDesc VARCHAR(64),
    FOREIGN KEY (Pcno) REFERENCES ProductCategory(Pcno)
);
CREATE TABLE ProductCategory (
    Pcno INT(9) PRIMARY KEY AUTO_INCREMENT,
    Pcname VARCHAR(64) NOT NULL
);
CREATE TABLE `ORDER` ( ID INT(9) PRIMARY KEY AUTO_INCREMENT, ProductName VARCHAR(64) NOT NULL, OrderQuantity INT(9) NOT NULL, SubmitDate DATE, EndDate DATE, Consignee VARCHAR(64), ContactInfo VARCHAR(64), Address VARCHAR(64), OrderStatus VARCHAR(16) );
 CREATE TABLE emp (
  ID INT(9) NOT NULL COMMENT 'ID',
  UName VARCHAR(64) DEFAULT NULL COMMENT '用户名',
  Pword VARCHAR(64) DEFAULT NULL COMMENT '密码',
  RName   VARCHAR(64) DEFAULT NULL COMMENT '真实姓名',
  RID   INT(1) DEFAULT NULL COMMENT '注册类型',
  CInfo VARCHAR(64) DEFAULT NULL COMMENT '联系方式',
  FName VARCHAR(64) DEFAULT NULL COMMENT '工厂名称',
  FProfile VARCHAR(64) DEFAULT NULL COMMENT '工厂简介',
  FStatus VARCHAR(16) DEFAULT NULL COMMENT '工厂状态',
  DelMark INT(1) NOT NULL DEFAULT '1' COMMENT '删除标记',
  PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=utf8;
CREATE TABLE Device (
  ID INT(9) PRIMARY KEY AUTO_INCREMENT,
  DeviceCode VARCHAR(64) NOT NULL,
  DeviceName VARCHAR(64) NOT NULL,
  DeviceType INT(9),
  DeviceSpec VARCHAR(64),
  ProductStatus VARCHAR(16),
  RentalStatus VARCHAR(16),
  Factory VARCHAR(16)
);
CREATE TABLE DeviceType (
  ID INT(9) PRIMARY KEY,
  TypeName VARCHAR(64) NOT NULL
);

